# Automatically download the latest release
auto-update: true
# Notify on join if a new version is available
update-notifications: true

# Debug logs
debug: false

# This prefix is used in most messages sent by the plugin
message-prefix: <dark_gray>[<gradient:#FF5CCC:#743296>Niso<dark_gray>] <reset>

# We use PlaceholderAPI placeholders and MiniMessage formatting in this configuration file.
# Recommended placeholders to download:
# /papi ecloud download Server
# /papi ecloud download Player

# Tablist configuration
tablist:
  enabled: false
  # this is the interval in ticks to update the tablist (20 ticks = 1 second)
  # keep this value between 20 and 1000 ticks to prevent issues
  update-interval: 100
  header: |-
    <dark_gray><strikethrough> ]                                                                  [ <reset>
    <gray>
    <gradient:#FF5CCC:#743296>mc.niso.moe
    <gray>
  footer: |-
    <gray>
    <gray>TPS: <green>%server_tps_15% <dark_gray>| <gray>Your Ping: <green>%player_ping%ms
    <gray>Players: <green>%server_online% <dark_gray>| <gray>Uptime: <green>%server_uptime%
    <gray>
    <dark_gray><strikethrough> ]                                                                  [ <reset>

# Welcome Message Configuration
welcome-message:
  enabled: false
  # Message sent only to the joining player
  personal-message:
    enabled: true
    message: <gray>Welcome to the server, <green>%player_name%<gray>!
  # Message broadcast to all players
  broadcast-message:
    enabled: true
    message: <dark_gray>[<green>+<dark_gray>] <gray>%player_name%

# Leave Message Configuration
leave-message:
  enabled: false
  # Message sent to all players
  broadcast-message:
    enabled: true
    message: <dark_gray>[<red>-<dark_gray>] <gray>%player_name%

# Chat format Configuration
chat-format:
  enabled: false
  # Example message: Nikki » Hello, world!
  format: <gray>%player_name% <dark_gray>» <reset>%message%

# Server MOTD Configuration
server-motd:
  enabled: false
  first-line: <gray>                     <rainbow><b>mc.niso.moe</b></rainbow>
  second-line: <gray>                         by Nikki</gray>

# Database configuration for PostgreSQL
#
# Commands to create the database and user:
# CREATE DATABASE minecraft;
# CREATE USER username WITH ENCRYPTED PASSWORD 'super_secret';
# GRANT ALL PRIVILEGES ON DATABASE minecraft to username;
#
database:
  host: localhost
  port: 5432
  database: minecraft
  username: username
  password: super_secret
  pool-size: 10
