# Automatically download the latest release
auto-update: true
# Debug logs
debug: false

# We use PlaceholderAPI placeholders and MiniMessage formatting in this configuration file.
# Recommended placeholders to download:
# /papi ecloud download Server
# /papi ecloud download Player

# Tablist configuration
tablist:
  enabled: false
  # this is the interval in ticks to update the tablist (20 ticks = 1 second)
  # keep this value between 20 and 1000 ticks to prevent issues
  update-interval: 100
  header: |-
    <dark_gray><strikethrough> ]                                                                  [ <reset>
    <gray>
    <gradient:#FF5CCC:#743296>mc.niso.moe
    <gray>
  footer: |-
    <gray>
    <gray>TPS: <green>%server_tps_15% <dark_gray>| <gray>Your Ping: <green>%player_ping%ms
    <gray>Players: <green>%server_online% <dark_gray>| <gray>Uptime: <green>%server_uptime%
    <gray>
    <dark_gray><strikethrough> ]                                                                  [ <reset>

# This prefix is used in all messages sent by the plugin.
message-prefix: <dark_gray>[<gradient:#FF5CCC:#743296>Niso<dark_gray>] <reset>

# Example message: [+] Nikki
welcome-message: <dark_gray>[<green>+<dark_gray>] <gray>%player_name%
leave-message: <dark_gray>[<red>-<dark_gray>] <gray>%player_name%

# Example message: Nikki » Hello, world!
chat-format: <gray>%player_name% <dark_gray>» <reset>%message%

server-motd: |-
  <b><red>A Minecraft Server</red></b>
  <gray>Powered by Niso</gray>

# Database configuration for PostgreSQL
# CREATE DATABASE minecraft;
# CREATE USER username WITH ENCRYPTED PASSWORD 'super_secret';
# GRANT ALL PRIVILEGES ON DATABASE minecraft to username;
database:
  host: localhost
  port: 5432
  database: minecraft
  user: username
  password: super_secret
  pool-size: 10
