name: NisoPlugin
version: '${project.version}'
main: moe.niso.NisoPlugin
api-version: '1.21'
authors: [ Nikki Sophie B. ]
website: https://niso.moe

softdepend: [ PlaceholderAPI, LuckPerms ]

commands:
  warp:
    description: Teleport to any configured place
    usage: /warp <set/delete/list/teleport> [name]
    aliases: [ w ]
    permission: niso.warp.use
  home:
    description: Teleport to your homes
    usage: /home <set/delete/list/teleport> [name]
    aliases: [ h ]
    permission: niso.home.use