name: NisoPlugin
version: '${project.version}'
main: moe.niso.NisoPlugin
api-version: '1.21'
authors: [ Nikki Sophie B. ]
website: https://niso.moe

softdepend: [ PlaceholderAPI, LuckPerms ]

commands:
  warp:
    description: Teleport to any configured place
    usage: /warp <set/delete/list/teleport> [name]
    aliases: [ w ]
    permission: niso.warp.use
  home:
    description: Teleport to your homes
    usage: /home <set/delete/list/teleport> [name]
    aliases: [ h ]
    permission: niso.home.use
  fly:
    description: Toggles the flight mode
    usage: /fly [player]
    permission: niso.fly.use
  vanish:
    description: Toggles the vanish mode
    usage: /vanish [player]
    permission: niso.vanish.use
  repair:
    description: Repairs the item in the main hand
    usage: /repair
    aliases: [ fix ]
    permission: niso.repair.use
  trash:
    description: Deletes the items you put into the inventory
    usage: /trash
    aliases: [ bin, garbage ]
    permission: niso.trash.use
  enderchest:
    description: Opens the enderchest
    usage: /enderchest
    aliases: [ ec ]
    permission: niso.enderchest.use
  feed:
    description: Restores the hunger bar
    usage: /feed
    aliases: [ eat, food ]
    permission: niso.feed.use